[package]
name = "object-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["cargo", "derive"] }
env_logger = "0.11.5"
fuser = "0.15.0"
libc = "0.2.162"
log = "0.4.22"
