name: build-publish
on:
  push:
    branches:
      - main
permissions: 
  contents: write
  packages: write 
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install-deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfuse3-dev

      - name: install-rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run-tests
        run: |
          cargo test --release
        continue-on-error: false
          
      - name: extract-version
        id: extract_version
        run: |
          version=$(grep '^version = ' Cargo.toml | head -1 | sed -E 's/version = "(.*)"/\1/')
          echo "::set-output name=version::$version"

      - name: build
        run: cargo build --release

      - name: package
        run: |
          mkdir -p dist
          tar -czvf dist/objectfs-v${{ steps.extract_version.outputs.version }}_amd64.tar.gz -C target/release objectfs
    
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: objectfs-targz
          path: dist/objectfs-v${{ steps.extract_version.outputs.version }}_amd64.tar.gz

  publish-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: objectfs-targz

      - name: create-release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ needs.build.outputs.version }}_amd64"
          release_name: "objectfs v${{ needs.build.outputs.version }}_amd64"
          body: "Release for objectfs v${{ needs.build.outputs.version }}_amd64"
          draft: false
          prerelease: false
  
      - name: upload-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: objectfs-v${{ needs.build.outputs.version }}_amd64.tar.gz
          asset_name: objectfs-v${{ needs.build.outputs.version }}_amd64.tar.gz
          asset_content_type: application/gzip

  publish-package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: objectfs-targz

    
      - name: extract-artifact
        run: |
          mkdir -p extracted
          tar -xzvf objectfs-v${{ needs.build.outputs.version }}_amd64.tar.gz -C extracted
  
      - name: create-package
        run: |
          mkdir -p deb-pkg/DEBIAN
          mkdir -p deb-pkg/usr/local/bin
          mkdir -p dist
  
          cat <<EOF > deb-pkg/DEBIAN/control
          Package: objectfs
          Version: ${{ needs.build.outputs.version }}
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: Evan Logsdon <evan@logsqua.red>
          Description: FUSE filesystem abstraction over cloud object storages: Amazon S3, Google Cloud Storage
          EOF
  
          cp extracted/objectfs deb-pkg/usr/local/bin/
          dpkg-deb --build deb-pkg dist/objectfs_${{ needs.build.outputs.version }}_amd64.deb
  
      - name: upload-package
        run: |
          curl -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
            -X POST \
            -H "Content-Type: application/vnd.debian.binary-package" \
            --data-binary @dist/objectfs_${{ needs.build.outputs.version }}_amd64.deb \
            "https://uploads.github.com/repos/${{ github.repository }}/packages/releases/assets?name=objectfs_${{ needs.build.outputs.version }}_amd64.deb"
  