name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install-rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run-tests
        run: cargo test --release