name: tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install-deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfuse3-dev

      - name: install-rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run-tests
        run: cargo test --release